# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install '

- task: CordovaCommand@1
  inputs:
    cordovaCommand: 'platform add ios'
    cwd: './src-cordova/'

- task: CordovaCommand@1
  inputs:
    cordovaCommand: 'build ios --device --release --buildConfig build.json'
    cwd: './src-cordova/'


  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './src-cordova/platforms/'
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/'
    artifactName: 'apks' 
    publishLocation: 'container'


# - task: DownloadSecureFile@1
#   name: caCertificate
#   inputs:
#     secureFile: 'ios_certificate.p12'
# - task: CordovaBuild@1
#   inputs:
#     platform: 'ios'
#     configuration: '$(Configuration)'
#     cordovaVersion: '9.0.0'
#     p12: '$(caCertificate.secureFilePath)'
#     p12pwd: '$(key.password)'
#     outputPattern: 'bin'
#     cwd: './src-cordova/'

# - task: AppStoreRelease@1
#   inputs:
#     authType: 'UserAndPass'
#     username: '$(username)'
#     password: '$(Password)'
#     appIdentifier: 'com.jamalong.app'
#     appType: 'iOS'
#     ipaPath: '**/*.ipa'
#     releaseTrack: 'TestFlight'
